name: do-something-with-token

on:
  workflow_dispatch:

jobs:
  use-api:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          curl -v \
          --header "Authorization: Bearer $GH_TOKEN" \
          "https://api.github.com/octocat"
