name: do-cmd-after-checkout

on:
  workflow_dispatch:
    inputs:
      cmd:
        description: what command to run
        type: string
        required: true
      repo:
        description: which repo to pull down
        type: string
        required: false
      full-checkout:
        description: full checkout?
        type: boolean
        required: false
        default: false

jobs:
  do-cmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo || github.repository }}
          fetch-depth: ${{ inputs.full-checkout && 0 || 1 }}

      - name: Show git DAG before anything
        run: git log --oneline --decorate --graph --all

      - run: ${{ inputs.cmd }}

      - name: Show git DAG after everything
        run: git log --oneline --decorate --graph --all
