name: do-cmd-on-push

on:
  push:
    branches:
      - 'do/**'

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::info::\$GITHUB_REF=\"$GITHUB_REF\""
          echo "::info::\$GITHUB_SHA=\"$GITHUB_SHA\""
          gh api -X GET repos/cawfeecake/my-calling-workflows/commits -f sha="$GITHUB_REF"
        env:
          GH_TOKEN: ${{ github.token }}
  sleep:
    needs: [ pre ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      TIME_TO_SLEEP: 120
  post:
    needs: [ sleep ]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::info::\$GITHUB_REF=\"$GITHUB_REF\""
          echo "::info::\$GITHUB_SHA=\"$GITHUB_SHA\""
          gh api -X GET repos/cawfeecake/my-calling-workflows/commits -f sha="$GITHUB_REF"
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v3
      - run: |
          git log --stat | head -32
