name: mock-build-and-failing-deploy

on:
  workflow_dispatch:
    inputs:
      BUILD_TIME:
        type: string
        required: true
        default: 5
      DEPLOYMENT_TIME:
        type: string
        required: true
        default: 5

jobs:
  build-job:
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      TIME_TO_SLEEP: ${{ inputs.BUILD_TIME }}
  fail-job:
    needs: [ build-job ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: dev
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
      SHOULD_FAIL: true
