name: mock-build-and-deploy-no-queue

on:
  workflow_dispatch:
    inputs:
      BUILD_TIME:
        description: build length (in seconds)
        type: string
        required: true
        default: 1
      DEPLOYMENT_TIME:
        description: deployment lengths (in seconds)
        type: string
        required: true
        default: 1
      FAIL_DEPLOYMENT_TO:
        description: if not "none", will have job that deploys to given environment fail
        type: choice
        options:
          - none
          - dev
          - int
          - prod
        required: true
        default: none

permissions:
  actions: write

jobs:
  build-job:
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      TIME_TO_SLEEP: ${{ inputs.BUILD_TIME }}
  deploy-dev:
    needs: [ build-job ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      CONCURRENCY_KEY: dev
      ENVIRONMENT: dev
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
      SHOULD_FAIL: ${{ inputs.FAIL_DEPLOYMENT_TO == 'dev' }}
  deploy-int:
    needs: [ deploy-dev ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      CONCURRENCY_KEY: int
      ENVIRONMENT: int
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
      SHOULD_FAIL: ${{ inputs.FAIL_DEPLOYMENT_TO == 'int' }}
  deploy-prod:
    needs: [ deploy-int ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      CONCURRENCY_KEY: prod
      ENVIRONMENT: prod
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
      SHOULD_FAIL: ${{ inputs.FAIL_DEPLOYMENT_TO == 'prod' }}
