name: multiple-sleep-calls-with-concurrency

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      DEPLOYMENT_TIME:
        type: string
        required: true
        default: 60

jobs:
  job0:
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: dev
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
  job1:
    needs: [ job0 ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: int
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
  job2:
    needs: [ job1 ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-when-unique-concurrency.yaml@main
    with:
      CONCURRENCY_KEY: prod
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
