name: mock-build-and-deploy

on:
  workflow_dispatch:
    inputs:
      BUILD_TIME:
        type: string
        required: true
        default: 10
      DEPLOYMENT_TIME:
        type: string
        required: true
        default: 10

jobs:
  build-job:
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      TIME_TO_SLEEP: ${{ inputs.BUILD_TIME }}
  determine-if-next:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'hello!'
  deploy-dev:
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: dev
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
  deploy-int:
    needs: [ deploy-dev ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: int
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
  deploy-prod:
    needs: [ deploy-int ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: prod
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
