name: mock-build-and-deploy

on:
  workflow_dispatch:
    inputs:
      BUILD_TIME:
        type: string
        required: true
        default: 5
      DEPLOYMENT_TIME:
        type: string
        required: true
        default: 5

jobs:
  build-job:
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep.yaml@main
    with:
      TIME_TO_SLEEP: ${{ inputs.BUILD_TIME }}
  determine-if-next:
    needs: [ build-job ]
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          current_workflow_runs=$(mktemp)
          gh run list -R ${{ github.repository }} -w ${{ github.workflow }} --json conclusion,createdAt,headBranch,headSha,number,startedAt,status,updatedAt > $current_workflow_runs
          echo '::group::current workflow runs'
          jq . $current_workflow_runs
          echo '::endgroup::'
          run_number=${{ github.run_number }}
          filtered_runs=$(jq --argjson number "$run_number" 'map(select(.conclusion | . == "") | select(.number != $number))' $current_workflow_runs)
          echo '::group::filtered workflow runs'
          jq . <<< $filtered_runs
          echo '::endgroup::'
          if [[ $(jq 'length' <<< $filtered_runs) > 0 ]]; then
            # TODO
            echo 'THERE ARE MORE PENDING WORKFLOWS THAN JUST ME'
          fi
  deploy-dev:
    needs: [ determine-if-next ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: dev
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
  deploy-int:
    needs: [ deploy-dev ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: int
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
  deploy-prod:
    needs: [ deploy-int ]
    uses: cawfeecake/my-reusable-workflows/.github/workflows/sleep-with-concurrency-key.yaml@main
    with:
      CONCURRENCY_KEY: prod
      TIME_TO_SLEEP: ${{ inputs.DEPLOYMENT_TIME }}
